/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.projectmanagement.gui.panel;

import static com.mycompany.projectmanagement.FilePreviewer.setPreviewPanel;
import com.mycompany.projectmanagement.UserController;
import static com.mycompany.projectmanagement.gui.panel.ReportSubmissionForm.FilePathField;
import java.awt.BorderLayout;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author yizun
 */
public class PdfPreviewer extends javax.swing.JPanel {

    public static JPanel previewPanel;
    private final JButton openButton;
    private final UserController userController;
    public static UserController.User user;

    /**
     * Creates new form PdfPreviewer
     */
    public PdfPreviewer() {
        initComponents();
        this.userController = new UserController();
        previewPanel = new JPanel(new BorderLayout());
        previewPanel.setSize(500, 500);
        openButton = new JButton("Attach");
        openButton.addActionListener(e -> openFile());
        setLayout(new BorderLayout());
        add(openButton, BorderLayout.NORTH);
        add(previewPanel, BorderLayout.CENTER);
    }

    private void openFile() {
        user = userController.new User();
        user.setUploadPath("\\src\\main\\java\\com\\mycompany\\projectmanagement\\report\\");
        File selectedFile = user.getSelectedFile();
        if (selectedFile != null) {
            setPreviewPanel(user.getSelectedFile());
            FilePathField.setText(user.getFullPath().toString());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
