/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.projectmanagement.gui.panel;

import com.mycompany.projectmanagement.gui.form.ReportSubmissionForm;
import com.mycompany.projectmanagement.FileController;
import com.mycompany.projectmanagement.UserController;
import java.awt.event.KeyEvent;
import org.json.JSONArray;

public class ReportSubmissionPanel extends javax.swing.JPanel {

    public final static String[] columns = {"ID", "student_id", "assessment_id", "supervisor", "second_marker", "status", "mark", "grade", "feedback", "file_path"};
    public String file, id;
    public UserController userController;
    private final FileController.FileService fs;
    private JSONArray reportArray, assessmentArray;

    public ReportSubmissionPanel() {
        initComponents();
        this.userController = new UserController();
        this.fs = new FileController.FileService();

    }

    public void setUser(String id) {
        this.id = id;
        refreshTable();
        submissionForm.setUser(id);
    }

    public void refreshTable() {
        UserController.User user = userController.new User();
        reportArray = user.seachUser(id, "report.txt", null);
        assessmentArray = user.seachUser(id, "assessment.txt", null);
        fs.showFileData(reportTable, ReportSubmissionPanel.columns, "report.txt", reportArray, 0);
        fs.showFileData(assessmentTable, ReportSubmissionForm.columns, "assessment.txt", assessmentArray, 0);
    }

//    public void setFile()
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        assessmentTable = new javax.swing.JTable();
        submissionForm = new com.mycompany.projectmanagement.gui.form.ReportSubmissionForm();
        assessmentSearchField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();

        assessmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        assessmentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assessmentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(assessmentTable);

        submissionForm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        assessmentSearchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                assessmentSearchFieldKeyPressed(evt);
            }
        });

        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        reportTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(reportTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(assessmentSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submissionForm, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(assessmentSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submissionForm, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assessmentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assessmentTableMouseClicked
        int SelectedRow = assessmentTable.getSelectedRow(); // Get the selected row index
        // Ensure a valid row is selected
        if (SelectedRow != -1) {
            int columnCount = assessmentTable.getColumnCount(); // Get the number of columns

            // Retrieve data from the table model for the clicked row
            Object[] rowData = new Object[columnCount];
            for (int columnIndex = 0; columnIndex < columnCount; columnIndex++) {
                rowData[columnIndex] = assessmentTable.getModel().getValueAt(SelectedRow, columnIndex);
            }

            // Pass the data to the edit form
            submissionForm.setAssessmentData(rowData);

        }
    }//GEN-LAST:event_assessmentTableMouseClicked

    private void assessmentSearchFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_assessmentSearchFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String searchValue = assessmentSearchField.getText();
            UserController.User user = userController.new User();
            JSONArray searchedArray = user.seachUser(searchValue, "assessment.txt", assessmentArray);
            fs.showFileData(assessmentTable, ReportSubmissionForm.columns, "assessment.txt", searchedArray, 0);
        }
    }//GEN-LAST:event_assessmentSearchFieldKeyPressed

    private void reportTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportTableMouseClicked
        // TODO add your handling code here:
        int SelectedRow = reportTable.getSelectedRow(); // Get the selected row index
        // Ensure a valid row is selected
        if (SelectedRow != -1) {
            int columnCount = reportTable.getColumnCount(); // Get the number of columns

            // Retrieve data from the table model for the clicked row
            Object[] rowData = new Object[columnCount];
            for (int columnIndex = 0; columnIndex < columnCount; columnIndex++) {
                rowData[columnIndex] = reportTable.getModel().getValueAt(SelectedRow, columnIndex);
            }

            // Pass the data to the edit form
            submissionForm.setReportData(rowData);

        }
    }//GEN-LAST:event_reportTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField assessmentSearchField;
    public static javax.swing.JTable assessmentTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable reportTable;
    private com.mycompany.projectmanagement.gui.form.ReportSubmissionForm submissionForm;
    // End of variables declaration//GEN-END:variables
}
