/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectmanagement.gui;

import com.mycompany.projectmanagement.gui.model.ModelHeader;
import com.mycompany.projectmanagement.FileController;
import com.mycompany.projectmanagement.UserController;
import com.mycompany.projectmanagement.gui.panel.AccountPanel;
import com.mycompany.projectmanagement.gui.panel.LecturerPanel;
import static com.mycompany.projectmanagement.gui.panel.LecturerPanel.importBtn;
import com.mycompany.projectmanagement.gui.model.ModelCard;
import com.mycompany.projectmanagement.gui.component.PieChart;
import com.mycompany.projectmanagement.gui.panel.StudentPanel;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author yizun
 */
public class AdminMenu extends javax.swing.JFrame {

    private final ArrayList<PieChart.PieChartData> pieChartData;
    private final FileController.FileService fs;
    int mouseX, mouseY;
    private File imagePath;

    /**
     * Creates new form MainMenu
     */
    public AdminMenu() {
        initComponents();
        this.fs = new FileController.FileService();
        this.pieChartData = new ArrayList<>();
        pieChartData.add(new PieChart.PieChartData("Role Percentage", "account.txt", "Role", new String[]{"student", "lecturer", "project manager"}));
        pieChartData.add(new PieChart.PieChartData("Entry Level Percentage", "student.txt", "Entry Level", new String[]{"Diploma", "Degree", "Masters Degree", "PhD", "Foundation"}));
        pieChartData.add(new PieChart.PieChartData("Student Gender Percentage", "student.txt", "Gender", new String[]{"Male", "Female"}));
        adminDashboard.pieChart1.setData(pieChartData, null);
        adminDashboard.pieChart1.refreshPieChart(pieChartData, null);

    }

    public void setHeader(String name, String title) {
        String projectDirectory = System.getProperty("user.dir");
        this.imagePath = new File(projectDirectory + "\\src\\main\\java\\com\\mycompany\\projectmanagement\\avatar\\default-avatar-icon-of-social-media-user-vector.jpg");
        header1.setData(new ModelHeader(title, name, new ImageIcon(imagePath.toString())));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header1 = new com.mycompany.projectmanagement.gui.component.Header();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        adminDashboard = new com.mycompany.projectmanagement.gui.dashboard.AdminDashboard();
        studentPanel = new com.mycompany.projectmanagement.gui.panel.StudentPanel();
        lecturerPanel = new com.mycompany.projectmanagement.gui.panel.LecturerPanel();
        accountPanel = new com.mycompany.projectmanagement.gui.panel.AccountPanel();
        manageCoursePanel = new com.mycompany.projectmanagement.gui.panel.ManageCoursePanel();
        studentMenu2 = new com.mycompany.projectmanagement.gui.model.SideNavigationMenu();
        dashboardBtn = new javax.swing.JButton();
        manageStudentBtn = new javax.swing.JButton();
        managePmBtn = new javax.swing.JButton();
        signoutBtn = new javax.swing.JButton();
        manageAccountBtn = new javax.swing.JButton();
        manageLecturerBtn = new javax.swing.JButton();
        manageAccountBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header1.setBackground(new java.awt.Color(51, 51, 51));
        header1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                header1MouseDragged(evt);
            }
        });
        header1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header1MousePressed(evt);
            }
        });
        getContentPane().add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1770, -1));

        jTabbedPane1.addTab("tab4", adminDashboard);
        jTabbedPane1.addTab("tab1", studentPanel);
        jTabbedPane1.addTab("tab2", lecturerPanel);
        jTabbedPane1.addTab("tab3", accountPanel);
        jTabbedPane1.addTab("tab5", manageCoursePanel);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 1590, 800));

        studentMenu2.setPreferredSize(new java.awt.Dimension(200, 672));

        dashboardBtn.setText("Dashboard");
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });

        manageStudentBtn.setText("Manage Student");
        manageStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStudentBtnActionPerformed(evt);
            }
        });

        managePmBtn.setText("Manage PM");
        managePmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePmBtnActionPerformed(evt);
            }
        });

        signoutBtn.setText("Sign Out");
        signoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutBtnActionPerformed(evt);
            }
        });

        manageAccountBtn.setText("Manage Account");
        manageAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAccountBtnActionPerformed(evt);
            }
        });

        manageLecturerBtn.setText("Manage Lecturer");
        manageLecturerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageLecturerBtnActionPerformed(evt);
            }
        });

        manageAccountBtn1.setText("Manage Course");
        manageAccountBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAccountBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentMenu2Layout = new javax.swing.GroupLayout(studentMenu2);
        studentMenu2.setLayout(studentMenu2Layout);
        studentMenu2Layout.setHorizontalGroup(
            studentMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
            .addComponent(manageStudentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(managePmBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageAccountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageLecturerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageAccountBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(signoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        studentMenu2Layout.setVerticalGroup(
            studentMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentMenu2Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(dashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(manageLecturerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(managePmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageAccountBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(signoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        getContentPane().add(studentMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        adminDashboard.initialCard();
        adminDashboard.pieChart1.refreshPieChart(pieChartData, null);
        fs.showFileData(LecturerPanel.userTable, LecturerPanel.columns, lecturerPanel.fileName, null, 1);
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void manageStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStudentBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        fs.showFileData(StudentPanel.userTable, StudentPanel.columns, "student.txt", null, 1);
    }//GEN-LAST:event_manageStudentBtnActionPerformed

    private void managePmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePmBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
        lecturerPanel.remove(importBtn);
        lecturerPanel.setFile("project_manager.txt");
        fs.showFileData(LecturerPanel.userTable, LecturerPanel.columns, lecturerPanel.fileName, null, 1);
    }//GEN-LAST:event_managePmBtnActionPerformed

    private void signoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutBtnActionPerformed
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_signoutBtnActionPerformed

    private void manageAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAccountBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
        fs.showFileData(AccountPanel.userTable, AccountPanel.columns, "account.txt", null, 0);

    }//GEN-LAST:event_manageAccountBtnActionPerformed

    private void manageLecturerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageLecturerBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
        lecturerPanel.add(importBtn);
        lecturerPanel.setFile("lecturer.txt");
        fs.showFileData(LecturerPanel.userTable, LecturerPanel.columns, "lecturer.txt", null, 1);
    }//GEN-LAST:event_manageLecturerBtnActionPerformed

    private void header1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header1MousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_header1MousePressed

    private void header1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header1MouseDragged
        // TODO add your handling code here:
        setLocation(evt.getXOnScreen() - mouseX, evt.getYOnScreen() - mouseY);
    }//GEN-LAST:event_header1MouseDragged

    private void manageAccountBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAccountBtn1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);

    }//GEN-LAST:event_manageAccountBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static com.mycompany.projectmanagement.gui.panel.AccountPanel accountPanel;
    private com.mycompany.projectmanagement.gui.dashboard.AdminDashboard adminDashboard;
    private javax.swing.JButton dashboardBtn;
    private com.mycompany.projectmanagement.gui.component.Header header1;
    public static javax.swing.JTabbedPane jTabbedPane1;
    public static com.mycompany.projectmanagement.gui.panel.LecturerPanel lecturerPanel;
    private javax.swing.JButton manageAccountBtn;
    private javax.swing.JButton manageAccountBtn1;
    private com.mycompany.projectmanagement.gui.panel.ManageCoursePanel manageCoursePanel;
    private javax.swing.JButton manageLecturerBtn;
    private javax.swing.JButton managePmBtn;
    private javax.swing.JButton manageStudentBtn;
    private javax.swing.JButton signoutBtn;
    private com.mycompany.projectmanagement.gui.model.SideNavigationMenu studentMenu2;
    public static com.mycompany.projectmanagement.gui.panel.StudentPanel studentPanel;
    // End of variables declaration//GEN-END:variables
}
