/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectmanagement.gui;

import com.mycompany.projectmanagement.FileController;
import com.mycompany.projectmanagement.gui.panel.AccountPanel;
import com.mycompany.projectmanagement.gui.panel.LecturerPanel;
import com.mycompany.projectmanagement.gui.panel.PieChart;
import com.mycompany.projectmanagement.gui.panel.StudentPanel;
import java.util.ArrayList;

/**
 *
 * @author yizun
 */
public class MainMenu extends javax.swing.JFrame {

    private final ArrayList<PieChart.PieChartData> pieChartData;
    private final FileController.FileService fs;
    int mouseX, mouseY;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        this.fs = new FileController.FileService();
        this.pieChartData = new ArrayList<>();
        pieChartData.add(new PieChart.PieChartData("Role Percentage", "account.txt", "Role", new String[]{"student", "lecturer", "project manager"}));
        pieChartData.add(new PieChart.PieChartData("Entry Level Percentage", "student.txt", "Entry Level", new String[]{"Diploma", "Degree", "Masters Degree", "PhD", "Foundation"}));
        pieChartData.add(new PieChart.PieChartData("Student Gender Percentage", "student.txt", "Gender", new String[]{"Male", "Female"}));
        adminDashboard1.pieChart1.setData(pieChartData);
        adminDashboard1.pieChart1.refreshPieChart(pieChartData);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header1 = new com.mycompany.projectmanagement.gui.Header();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        adminDashboard1 = new com.mycompany.projectmanagement.gui.panel.AdminDashboard();
        studentList = new com.mycompany.projectmanagement.gui.panel.StudentPanel();
        lecturerList = new com.mycompany.projectmanagement.gui.panel.LecturerPanel();
        accountList = new com.mycompany.projectmanagement.gui.panel.AccountPanel();
        jPanel2 = new javax.swing.JPanel();
        manageStudentBtn = new javax.swing.JButton();
        manageLecturerBtn = new javax.swing.JButton();
        manageAccountBtn = new javax.swing.JButton();
        signOutBtn = new javax.swing.JButton();
        managePMBtn = new javax.swing.JButton();
        dashboarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header1.setBackground(new java.awt.Color(51, 51, 51));
        header1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                header1MouseDragged(evt);
            }
        });
        header1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header1MousePressed(evt);
            }
        });
        getContentPane().add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1770, -1));

        jTabbedPane1.addTab("tab4", adminDashboard1);
        jTabbedPane1.addTab("tab1", studentList);
        jTabbedPane1.addTab("tab2", lecturerList);
        jTabbedPane1.addTab("tab3", accountList);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 1590, 800));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        manageStudentBtn.setText("Manage Student");
        manageStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStudentBtnActionPerformed(evt);
            }
        });

        manageLecturerBtn.setText("Manage Lecturer");
        manageLecturerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageLecturerBtnActionPerformed(evt);
            }
        });

        manageAccountBtn.setText("Manage Account");
        manageAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAccountBtnActionPerformed(evt);
            }
        });

        signOutBtn.setText("Sign Out");
        signOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutBtnActionPerformed(evt);
            }
        });

        managePMBtn.setText("Manage PM");
        managePMBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePMBtnActionPerformed(evt);
            }
        });

        dashboarBtn.setText("Dashboard");
        dashboarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dashboarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(managePMBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageLecturerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageAccountBtn))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(dashboarBtn)
                .addGap(18, 18, 18)
                .addComponent(manageStudentBtn)
                .addGap(18, 18, 18)
                .addComponent(manageLecturerBtn)
                .addGap(18, 18, 18)
                .addComponent(managePMBtn)
                .addGap(18, 18, 18)
                .addComponent(manageAccountBtn)
                .addGap(18, 18, 18)
                .addComponent(signOutBtn)
                .addContainerGap(460, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageLecturerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageLecturerBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
        lecturerList.setFile("lecturer.txt");
        fs.showFileData(LecturerPanel.userTable, LecturerPanel.columns, "lecturer.txt", null, 1);
    }//GEN-LAST:event_manageLecturerBtnActionPerformed

    private void manageStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStudentBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        fs.showFileData(StudentPanel.userTable, StudentPanel.columns, "student.txt", null, 1);

    }//GEN-LAST:event_manageStudentBtnActionPerformed

    private void manageAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAccountBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
        fs.showFileData(AccountPanel.userTable, AccountPanel.columns, "account.txt", null, 0);
    }//GEN-LAST:event_manageAccountBtnActionPerformed

    private void signOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutBtnActionPerformed
        // TODO add your handling code here:
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_signOutBtnActionPerformed

    private void managePMBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePMBtnActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
        lecturerList.setFile("project_manager.txt");
        fs.showFileData(LecturerPanel.userTable, LecturerPanel.columns, lecturerList.fileName, null, 1);
    }//GEN-LAST:event_managePMBtnActionPerformed

    private void dashboarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboarBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        adminDashboard1.initialCard();
        adminDashboard1.pieChart1.refreshPieChart(pieChartData);
        fs.showFileData(LecturerPanel.userTable, LecturerPanel.columns, lecturerList.fileName, null, 1);
    }//GEN-LAST:event_dashboarBtnActionPerformed

    private void header1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header1MouseDragged
        // TODO add your handling code here:
        setLocation(evt.getXOnScreen() - mouseX, evt.getYOnScreen() - mouseY);
    }//GEN-LAST:event_header1MouseDragged

    private void header1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header1MousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_header1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static com.mycompany.projectmanagement.gui.panel.AccountPanel accountList;
    private com.mycompany.projectmanagement.gui.panel.AdminDashboard adminDashboard1;
    private javax.swing.JButton dashboarBtn;
    private com.mycompany.projectmanagement.gui.Header header1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JTabbedPane jTabbedPane1;
    public static com.mycompany.projectmanagement.gui.panel.LecturerPanel lecturerList;
    private javax.swing.JButton manageAccountBtn;
    private javax.swing.JButton manageLecturerBtn;
    private javax.swing.JButton managePMBtn;
    private javax.swing.JButton manageStudentBtn;
    private javax.swing.JButton signOutBtn;
    public static com.mycompany.projectmanagement.gui.panel.StudentPanel studentList;
    // End of variables declaration//GEN-END:variables
}
