package com.mycompany.projectmanagement.gui;

import com.mycompany.projectmanagement.FileController;
import static com.mycompany.projectmanagement.JtreeController.buildTree;
import static com.mycompany.projectmanagement.gui.ManageCourseForm.courseField;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;
import javax.swing.tree.TreePath;
import org.json.JSONArray;
import org.json.JSONObject;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author yizun
 */
public class ManageCoursePanel extends javax.swing.JPanel {

    public static DefaultMutableTreeNode node, root;

    /**
     * Creates new form ManageCoursePanel
     */
    public ManageCoursePanel() {
        initComponents();
        FileController.FileService fs = new FileController.FileService();
        JSONObject jsonObject = (JSONObject) fs.readData("course.txt", "object");
        if (jsonObject != null) {
            JSONArray jsonArray = jsonObject.getJSONArray("areas");

            // Create the root node
            root = new DefaultMutableTreeNode("Root");

            // Build the tree structure
            buildTree(root, jsonArray);

            // Create the tree model and set it to the JTree
            DefaultTreeModel treeModel = new DefaultTreeModel(root);
            jTree1.setModel(treeModel);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        manageCourseForm1 = new com.mycompany.projectmanagement.gui.ManageCourseForm();

        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTree1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageCourseForm1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageCourseForm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        // TODO add your handling code here:
        TreePath selectedPath = jTree1.getSelectionPath();
        if (selectedPath != null) {
            DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) selectedPath.getLastPathComponent();
            if (selectedNode instanceof DefaultMutableTreeNode) {
                node = selectedNode;
                courseField.setText(node.toString());

            }
        }
    }//GEN-LAST:event_jTree1MouseClicked

    private void jTree1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MousePressed
        // TODO add your handling code here:
        if (SwingUtilities.isRightMouseButton(evt)) {
            if (node != null) {
                int confirmDialogResult = JOptionPane.showConfirmDialog(jTree1, "Are you sure you want to delete this node?", "Delete Confirmation", JOptionPane.YES_NO_OPTION
                );
                if (confirmDialogResult == JOptionPane.YES_OPTION) {
                    // Remove the node from the parent
                    MutableTreeNode parent = (MutableTreeNode) node.getParent();
                    parent.remove(node);
                    ((DefaultTreeModel) jTree1.getModel()).nodeStructureChanged(parent);
                }
            }

        }
    }//GEN-LAST:event_jTree1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTree jTree1;
    private com.mycompany.projectmanagement.gui.ManageCourseForm manageCourseForm1;
    // End of variables declaration//GEN-END:variables
}
