/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.projectmanagement.gui.dashboard;

import com.mycompany.projectmanagement.FileController;
import com.mycompany.projectmanagement.UserController;
import com.mycompany.projectmanagement.gui.panel.PresentationRquestPanel;
import com.mycompany.projectmanagement.gui.panel.ReportSubmissionPanel;
import java.awt.event.KeyEvent;
import org.json.JSONArray;

/**
 *
 * @author Asus
 */
public class StudentDashboard extends javax.swing.JPanel {

    private String id;
    private final FileController.FileService fs;
    private final UserController userController;
    private JSONArray reportArray;
    private JSONArray requestArray;

    /**
     * Creates new form StudentDashboardList
     */
    public StudentDashboard() {
        initComponents();
        this.fs = new FileController.FileService();
        this.userController = new UserController();

    }

    public void setUser(String id) {
        this.id = id;
        refreshTable();
    }

    public void refreshTable() {
        UserController.User user = userController.new User();
        requestArray = user.seachUser(id, "request.txt", null);
        reportArray = user.seachUser(id, "report.txt", null);
        fs.showFileData(SubmissionTable, ReportSubmissionPanel.columns, "report.txt", reportArray, 1);
        fs.showFileData(BookingTable, PresentationRquestPanel.columns, "request.txt", requestArray, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        SubmissionTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        BookingTable = new javax.swing.JTable();
        card1 = new com.mycompany.projectmanagement.gui.component.Card();
        card2 = new com.mycompany.projectmanagement.gui.component.Card();
        pieChart1 = new com.mycompany.projectmanagement.gui.component.PieChart();
        submissionSearchField = new javax.swing.JTextField();
        bookingSearchField = new javax.swing.JTextField();

        SubmissionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Assessment Type", "Supervisor", "Second Marker", "Due Date", "Module", "File Path"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(SubmissionTable);

        BookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(BookingTable);

        card1.setColor1(new java.awt.Color(255, 204, 204));

        card2.setColor1(new java.awt.Color(204, 204, 255));

        submissionSearchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                submissionSearchFieldKeyPressed(evt);
            }
        });

        bookingSearchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bookingSearchFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(card2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(card1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pieChart1, javax.swing.GroupLayout.DEFAULT_SIZE, 1123, Short.MAX_VALUE))
                        .addComponent(bookingSearchField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2))
                    .addComponent(submissionSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(card2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(card1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pieChart1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submissionSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submissionSearchFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_submissionSearchFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String searchValue = submissionSearchField.getText();
            UserController.User user = userController.new User();
            JSONArray searchedArray = user.seachUser(searchValue, "report.txt", reportArray);
            fs.showFileData(SubmissionTable, ReportSubmissionPanel.columns, "report.txt", searchedArray, 0);
        }
    }//GEN-LAST:event_submissionSearchFieldKeyPressed

    private void bookingSearchFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bookingSearchFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String searchValue = bookingSearchField.getText();
            UserController.User user = userController.new User();
            JSONArray searchedArray = user.seachUser(searchValue, "request.txt", requestArray);
            fs.showFileData(BookingTable, PresentationRquestPanel.columns, "request.txt", searchedArray, 0);
        }
    }//GEN-LAST:event_bookingSearchFieldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable BookingTable;
    public static javax.swing.JTable SubmissionTable;
    private javax.swing.JTextField bookingSearchField;
    public static com.mycompany.projectmanagement.gui.component.Card card1;
    public static com.mycompany.projectmanagement.gui.component.Card card2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public com.mycompany.projectmanagement.gui.component.PieChart pieChart1;
    private javax.swing.JTextField submissionSearchField;
    // End of variables declaration//GEN-END:variables
}
